version: '3.4'

volumes:
  datafiles:

services:
  db:
    image: myawardprogram-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: MySql.Dockerfile
    volumes:
      - datafiles:/var/lib/mysql
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: mysqlpassroot
      MYSQL_USER: docker
      MYSQL_PASSWORD: mysqlpass
      MYSQL_DATABASE: myawardprogram
    ports:
      - "3308:3306"

  myawardprogram.api:
    image: myawardprogramapi
    build:
      context: .
      dockerfile: Api.Dockerfile
    environment:
      - DBHOST=db
      - DBPORT=3306
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "44300:80"
    depends_on:
      - db