version: '3.4'

services:
  db:
    image: myawardprogram-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build: 
      context: .
      dockerfile: src/MyAwardProgram.Api/MySql.Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: mysqlpassroot
      MYSQL_USER: docker
      MYSQL_PASSWORD: mysqlpass
      MYSQL_DATABASE: myawardprogram
    ports:
      - 3308:3306
    networks:
      - my-network

  myawardprogram.api:
    image: ${DOCKER_REGISTRY-}myawardprogramapi
    build:
      context: .
      dockerfile: src/MyAwardProgram.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Develop
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
